### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by chemars** [statrstart/statrstart.github.io#1]
Hello, when I was looking for a program to calculate the JMA seismic intensity, I found your [article](https://statrstart.github.io/2015/04/19/R%E3%81%A7%E8%A8%88%E6%B8%AC%E9%9C%87%E5%BA%A6%E3%81%AE%E7%AE%97%E5%87%BA/) ([original file](https://github.com/statrstart/statrstart.github.io/blob/master/2015/04/19/R%E3%81%A7%E8%A8%88%E6%B8%AC%E9%9C%87%E5%BA%A6%E3%81%AE%E7%AE%97%E5%87%BA/index.html)). Can I rewrite your code to GNU Octave format and publish it on GitHub? I will indicate the source.
In addition, can I rewrite the program to calculate the Fujian Earthquake Agency instrumental seismic intensity and also publish it on GitHub?

**Comment by statrstart** [comment]
Sure, go ahead.

**Comment by chemars** [comment]
Thank you. This is the [repository](https://github.com/chemars/Seismic-Intensity-Scales).

**Comment by chemars** [comment]
When I showed the program to my friend, he asked what is the license for the program. In my repository, `jma.m` and `fjea.m` are rewritten from your code. Which license is your code used for?

**Comment by statrstart** [comment]
Thank you for your e-mail.
It is licensed under CC0.

以下、日本語(Japanese)で
自分の書いたコードをrewriteしてもらえるとは思ってもいませんでしたので「Which license is your code used for?」という質問には正直戸惑ってしまいます。
当該コードは
計測震度の算出方法
http://www.data.jma.go.jp/svd/eqev/data/kyoshin/kaisetsu/calc_sindo.htm
に従ってRでの計算方法を示したしただけなのでそもそもなにかの権利が発生するのかどうかも正直わかりません。実際、他の言語（例えばFORTRAN ）でプログラムを作成されている方も複数おられます。
（「計測震度 プログラム」で検索してみてください）
質問を頂いてから自分なりに調べた結果、あえて質問に答えるとすると「CC0  license」が適当かと思います。

**Comment by chemars** [comment]
之前我想寫能夠計算地震震度的程式，所以就在網路上找相關資料。我找到您的文章，覺得內容清楚且詳細，所以就想改寫您的程式碼以在GNU Octave執行，我曾經詢問過您能否改寫與發布在Github上。後來我把修改後的程式拿給朋友，看看有沒有什麼問題，在討論的途中有提到關於授權條款的問題，我沒看到您的程式碼所用的授權條款，所以再次詢問您。如果有授權條款，只要我遵守授權條款，我就能利用或修改您的程式碼，參考這篇[文章](https://choosealicense.com/no-permission/)。
另外您以日文所寫的回覆，因為我不會日文，所以是靠機器翻譯理解，可能會有理解錯誤。日本氣象廳公布了計測震度的計算方法，您根據這個計算方法寫出了程式，就您所寫的程式碼，您應該是有著作權的，其他人用其他程式語言寫的程式與您的權利無關。您所寫的程式碼您可以自行決定要採用何種授權條款。我寫的程式我是想採用MIT License，包括`jma.m`和`fjea.m`。我會註明原本您所寫的程式碼的授權條款是CC0。


I wanted to write a program that can calculate the seismic intensity, so I found relevant information on the Internet. I found your article and thought it was clear and detailed, so I wanted to rewrite your code to run on GNU Octave. I once asked if I could rewrite and post it on Github. Later, I showed the modified program to my friend to see if there was any problem. In the discussion, there was a issue about license. I didn't see the license for your code, so I asked you again. If there is a license, I can use or modify your code as long as I follow the license, refer to this [article](https://choosealicense.com/no-permission/).
In addition, you reply in Japanese, because I don't know Japanese, so I understand it by machine translation, and there may be misunderstandings. The Japan Meteorological Agency published a calculation method for instrumental seismic intensity, and you wrote a program based on this calculation method. You should have copyright for the code you write. Others write programs in other programming languages are not related to your rights. You can decide which license for your code. I want to choose the MIT License for my program, including `jma.m` and `fjea.m`. I will indicate that the code you originally wrote is licensed under CC0.

**Comment by statrstart** [comment]
メールありがとう。
昨日は日本語を翻訳せずに送ってしまってごめんなさい。
ライセンス関係、難しいですね。
このようなメッセージのやり取りも初めてのことなので、スムーズな返答ができなくてごめんなさい。
「我會註明原本您所寫的程式碼的授權條款是CC0。」
（ I will indicate that the code you originally wrote is licensed under CC0.）　とのこと了承しました。
僕の書いたプログラムが役に立ってうれしいです。

Thank you for your message.
I'm sorry for sending Japanese without translation yesterday.
Licensing relationship is difficult, is not it?
It's also the first time to exchange such a message, so I'm sorry I couldn't respond smoothly.
I understand that "I will indicate that the code you originally wrote is licensed under CC0."
I'm glad that the program I wrote is useful.

**Comment by chemars** [comment]
Thank you. I have added the license to the [repository](https://github.com/chemars/Seismic-Intensity-Scales).
